# https://github.com/rust-lang/cargo/pull/10473

[unstable]
multitarget = true

[build]
target=["i686-pc-windows-msvc","x86_64-pc-windows-msvc"]
#target=["x86_64-pc-windows-msvc"]
#target=["i686-pc-windows-msvc"]